Refactor GitHub Actions workflow for proxy scraper
Updated the GitHub Actions workflow to improve the upload process for proxy files and added a tag for latest updates.

diff --git a/.github/workflows/proxyscraper.yml b/.github/workflows/proxyscraper.yml
--- a/.github/workflows/proxyscraper.yml
+++ b/.github/workflows/proxyscraper.yml
@@ -40,7 +40,7 @@ jobs:
 
       - name: 🕸️ Run scraping script
         run: |
-          python Files/proxy_scraper.py || { echo "Scraper failed, check logs"; exit 1; }  # اصلاح نام فایل به proxy_scraper.py
+          python Files/proxy_scraper.py || { echo "Scraper failed, check logs"; exit 1; }
 
       - name: 📂 Check directory contents
         run: |
@@ -81,18 +81,20 @@ jobs:
 
       - name: 📦 Upload proxy files to Releases
         uses: softprops/action-gh-release@v3
-        if: github.event_name != 'pull_request' 
+        if: github.event_name != 'pull_request'
         with:
+          tag_name: latest-proxy-update
+          name: Latest Proxy Lists
+          body: |
+            Updated at: ${{ github.event.repository.updated_at }}
+            Generated by Proxy Scraper
           files: |
             proxy_output/SOCKS5.txt
             proxy_output/SOCKS4.txt
             proxy_output/HTTPS.txt
             Files/requirements.txt
-          tag_name: latest
-          name: Latest Proxy Lists
-          body: |
-            Updated proxy lists generated by ProxyProwler at ${{ github.event.repository.updated_at }}.
           draft: false
           prerelease: false
+          make_latest: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
